debug: true
swagger:
  enable: true

server:
  port: 8084

spring:
  application:
    name: nacos-discovery-config
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

management:
  endpoints:
    web:
      exposure:
        include: '*'
